# Generated by Django 3.0.8 on 2021-09-07 04:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.comment_directory_path),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.user_directory_path),
        ),
    ]
