# Generated by Django 3.0.8 on 2021-09-11 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='shared_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='shared_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to=settings.AUTH_USER_MODEL),
        ),
    ]
